# Generated by Django 3.2.7 on 2021-09-23 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=8)),
                ('role', models.CharField(max_length=10)),
                ('attendance', models.CharField(max_length=10)),
            ],
        ),
    ]
